version: '3.8'

services:
  redis:
    image: redis:7-alpine
    expose:
      - '6379'
    networks:
      - coolify

  backend:
    build: ./backend
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    expose:
      - '8000'
    env_file:
      - .env
    environment:
      - RUN_MIGRATIONS=true
    depends_on:
      - redis
    networks:
      - coolify
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.rule=Host(`apitest.birthdayremainder.online`)
      - traefik.http.routers.backend.entrypoints=websecure
      - traefik.http.routers.backend.tls.certresolver=letsencrypt
      - traefik.http.services.backend.loadbalancer.server.port=8000

  celery_worker:
    build: ./backend
    command: celery -A core worker -l info
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - coolify

  celery_beat:
    build: ./backend
    command: celery -A core beat -l info
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - coolify

  frontend:
    build: ./frontend
    expose:
      - '3000'
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - coolify
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=Host(`test.birthdayremainder.online`)
      - traefik.http.routers.frontend.entrypoints=websecure
      - traefik.http.routers.frontend.tls.certresolver=letsencrypt
      - traefik.http.services.frontend.loadbalancer.server.port=3000

networks:
  coolify:
    external: true
