# Generated by Django 5.0.4 on 2026-05-09 07:52

import birthdays.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='birthdayrecord',
            options={'ordering': ['month', 'day']},
        ),
        migrations.RemoveField(
            model_name='birthdayrecord',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='birthdayrecord',
            name='day',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='birthdayrecord',
            name='month',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='birthdayrecord',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='birthdayrecord',
            name='contact_email',
            field=birthdays.models.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='birthdayrecord',
            name='friend_name',
            field=birthdays.models.EncryptedCharField(),
        ),
    ]
