# Generated by Django 5.2 on 2026-05-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0002_alter_birthdayrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdayrecord',
            name='group',
            field=models.CharField(default='Friends', max_length=50),
        ),
        migrations.AddField(
            model_name='birthdayrecord',
            name='relationship',
            field=models.CharField(default='friend', max_length=50),
        ),
    ]
