# Generated by Django 5.2 on 2026-05-10 06:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(default='Shopping', max_length=50)),
                ('discount_text', models.CharField(blank=True, max_length=50, null=True)),
                ('brand_color', models.CharField(default='#6366f1', max_length=7)),
                ('link', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('icon_type', models.CharField(default='ShoppingBag', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
