# Generated by Django 5.0.4 on 2026-05-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_smart_reminders_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reminder_days_before',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reminder_time',
            field=models.TimeField(default='09:00:00'),
        ),
    ]
