# Generated by Django 5.2 on 2026-05-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_smart_reminders_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='streak_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_wishes_sent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
