name: Birthday Reminder

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "58 6 * * *"  
    - cron: "0 18 * * *"   

env:
  SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
  SMTP_PORT: ${{ secrets.SMTP_PORT }}
  SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
  RECEIVER_EMAILS: ${{ secrets.RECEIVER_EMAILS }}
  PASSWORD: ${{ secrets.PASSWORD }}

jobs:
  reminder:
    name: Birthday Reminder
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python Script
        run: python birthday.py
